<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[POST Response Code :  401]]>
    </line>
    <line>
      <![CDATA[POST Response Message : Unauthorized]]>
    </line>
    <line>
      <![CDATA[POST Worked ]]>
    </line>
  </reporter-output>
  <suite started-at="2020-06-03T15:56:53Z" name="Default suite" finished-at="2020-06-03T15:56:56Z" duration-ms="3235">
    <groups>
    </groups>
    <test started-at="2020-06-03T15:56:53Z" name="Default test" finished-at="2020-06-03T15:56:56Z" duration-ms="3235">
      <class name="com.atmecs.api.get.testscripts.oauth2.identserver.TC_01_Get_Response_Of_Ident_Server">
        <test-method signature="postTask()[pri:0, instance:com.atmecs.api.get.testscripts.oauth2.identserver.TC_01_Get_Response_Of_Ident_Server@28975c28]" started-at="2020-06-03T15:56:53Z" name="postTask" finished-at="2020-06-03T15:56:56Z" duration-ms="3195" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[INFO: Status Code Validation Failed. expected [201] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: INFO: Status Code Validation Failed. expected [201] but found [401]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.atmecs.api.get.testscripts.oauth2.identserver.TC_01_Get_Response_Of_Ident_Server.postTask(TC_01_Get_Response_Of_Ident_Server.java:367)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[POST Response Code :  401]]>
            </line>
            <line>
              <![CDATA[POST Response Message : Unauthorized]]>
            </line>
            <line>
              <![CDATA[POST Worked ]]>
            </line>
          </reporter-output>
        </test-method> <!-- postTask -->
      </class> <!-- com.atmecs.api.get.testscripts.oauth2.identserver.TC_01_Get_Response_Of_Ident_Server -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
